name: Falce&Camogli
author: Junkarlo
description:  Di vita, di strada, disgrazie
avatar: /images/avatar.png
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github:
  instagram:
  linkedin: 
  pinterest:
  rss: rss
  twitter:
  stackoverflow: 
  youtube:
  googleplus:
  playconsole:
disqus: 
google_analytics: UA-43339302-11
url:
enforce_ssl:

permalink: /:title/
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

include: ['_pages']

paginate: 6
paginate_path: /page:num/

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

